### PR TITLE
Fix parsing failure on WITH clauses

### LINKED ISSUE #528: Parsing fails when there isn't default schema
I notice there is error on parsing TrinoQueryProperties file, when there isn’t default schema set while using WITH clause
sql is sth like this where it has default catalog, but not default schema for temporary table created with WITH.

```SQL
WITH ctr AS (
  SELECT sscode,
         SUM(sc) AS sc,
  FROM mysql_laim_data.lboard_data.ctr
  WHERE ...
), t_summary_by_sscode AS (
SELECT ...
FROM
(
  SELECT *
  FROM ctr LEFT OUTER JOIN ctr_before_one
  USING (sscode)
  ) LEFT OUTER JOIN ctr_before_two
  USING (sscode)
)

SELECT sscode,
       QC
FROM t_summary_by_sscode
...
```

Image
Image

### PR DESCRIPTION
**Pull request by Chaho12**
## Description

Fix parsing failure on WITH clauses. 

## Additional context and related issues

- close #528 

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
* Fix parsing failures on WITH clauses. ({issue}`528`)
```

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
The changes look ok but overall I think we are doing the wrong thing here .. we really should not try to parse the query since we are missing the full context .. only the coordinator really has that. I think in the long run we have to go down the route of farming this work out to a coordinator .. otherwise we end up pulling everything in and duplicating it so we kinda end up with the whole parsing code again.

File: gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java [hunk 1]
```diff
@@ -201,12 +205,18 @@ else if (statement instanceof ExecuteImmediate executeImmediate) {
 
             getNames(statement, tableBuilder, catalogBuilder, schemaBuilder, catalogSchemaBuilder);
             tables = tableBuilder.build();
-            catalogBuilder.addAll(tables.stream().map(q -> q.getParts().getFirst()).iterator());
+
+            Set<QualifiedName> filteredTables = ImmutableSet.copyOf(
+                    tables.stream()
+                            .filter(table -> !temporaryTables.contains(table))
+                            .collect(Collectors.toSet()));
```
Comment (ebyhr) [inline gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java:212]: This can be:
```java
            Set<QualifiedName> filteredTables = tables.stream()
                            .filter(table -> !temporaryTables.contains(table))
                            .collect(toImmutableSet());
```

**Review by ebyhr — CHANGES_REQUESTED** [review]
Please add a test.

**Comment by Chaho12** [comment]
> we really should not try to parse the query since we are missing the full context .. only the coordinator really has that.

I agree, even if it is quite helpful information. We should talk more on this next time.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 2]
```diff
@@ -404,6 +405,36 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+    @Test
+    void testWithQueryNameExcluded()
+            throws IOException
+    {
+        String query = """
+                WITH dos AS (SELECT c1 from cat.schem.tbl1),
+                uno as (SELECT c1 FROM dos)
+                SELECT c1 FROM uno, dos
+                """;
+        BufferedReader bufferedReader = new BufferedReader(new StringReader(query));
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:417]: nit: No need to reuse `bufferedReader`. I would inline this variable.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 3]
```diff
@@ -404,6 +405,36 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+        HttpServletRequest mockRequestWithDefaults = prepareMockRequest();
+        when(mockRequestWithDefaults.getReader()).thenReturn(bufferedReader);
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_CATALOG_HEADER_NAME)).thenReturn(DEFAULT_CATALOG);
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_SCHEMA_HEADER_NAME)).thenReturn(DEFAULT_SCHEMA);
+
+        TrinoQueryProperties trinoQueryPropertiesWithDefaults = new TrinoQueryProperties(mockRequestWithDefaults, requestAnalyzerConfig);
+
+        assertThat(trinoQueryPropertiesWithDefaults.tablesContains(format("%s.%s.%s", DEFAULT_CATALOG, DEFAULT_SCHEMA, "uno"))).isFalse();
+        assertThat(trinoQueryPropertiesWithDefaults.tablesContains(format("%s.%s.%s", DEFAULT_CATALOG, DEFAULT_SCHEMA, "does"))).isFalse();
+        assertThat(trinoQueryPropertiesWithDefaults.tablesContains("cat.schem.tbl1")).isTrue();
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:427]: We can't understand the entire tales in `trinoQueryPropertiesWithDefaults` from these assertions. Please use `getTables()` instead.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 4]
```diff
@@ -404,6 +405,36 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+
+        HttpServletRequest mockRequestNoDefaults = prepareMockRequest();
+        bufferedReader = new BufferedReader(new StringReader(query));
+        when(mockRequestNoDefaults.getReader()).thenReturn(bufferedReader);
+
+        TrinoQueryProperties trinoQueryPropertiesNoDefaults = new TrinoQueryProperties(mockRequestNoDefaults, requestAnalyzerConfig);
+        assertThat(trinoQueryPropertiesNoDefaults.getTables()).hasSize(3);
+        assertThat(trinoQueryPropertiesNoDefaults.tablesContains("cat.schem.tbl1")).isTrue();
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:435]: ditto.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java (hunk 2 above)
Comment (Chaho12) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:417]: this is reused in line 431 so, and i think both is needed as we have two TrinoQueryProperties objects

Comment (ebyhr) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:417]: I know it's reused in 431. The question is why do we need to reuse the object?

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 5]
```diff
@@ -404,6 +405,38 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+        when(mockRequestWithDefaults.getReader()).thenReturn(bufferedReader);
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_CATALOG_HEADER_NAME)).thenReturn(DEFAULT_CATALOG);
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_SCHEMA_HEADER_NAME)).thenReturn(DEFAULT_SCHEMA);
+
+        TrinoQueryProperties trinoQueryPropertiesWithDefaults = new TrinoQueryProperties(mockRequestWithDefaults, requestAnalyzerConfig);
+
+        Set<QualifiedName> tablesWithDefaults = trinoQueryPropertiesWithDefaults.getTables();
+        assertThat(tablesWithDefaults.contains(QualifiedName.of(DEFAULT_CATALOG, DEFAULT_SCHEMA, "uno"))).isFalse();
+        assertThat(tablesWithDefaults.contains(QualifiedName.of(DEFAULT_CATALOG, DEFAULT_SCHEMA, "does"))).isFalse();
+        assertThat(tablesWithDefaults.contains(QualifiedName.of("cat", "schem", "tbl1"))).isTrue();
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:428]: Please use `containsExactly` or any other list-assertions.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 6]
```diff
@@ -404,6 +405,38 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+
+        HttpServletRequest mockRequestNoDefaults = prepareMockRequest();
+        bufferedReader = new BufferedReader(new StringReader(query));
+        when(mockRequestNoDefaults.getReader()).thenReturn(bufferedReader);
+
+        TrinoQueryProperties trinoQueryPropertiesNoDefaults = new TrinoQueryProperties(mockRequestNoDefaults, requestAnalyzerConfig);
+        Set<QualifiedName> tablesNoDefaults = trinoQueryPropertiesNoDefaults.getTables();
+        assertThat(tablesNoDefaults).hasSize(3);
+        assertThat(tablesNoDefaults.contains(QualifiedName.of("cat", "schem", "tbl1"))).isTrue();
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:437]: Please use `containsExactly` or any other list-assertions.

**Review by ebyhr — CHANGES_REQUESTED** [review]

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java (hunk 2 above)
Comment (Chaho12) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:417]: i don't quite understand your point. do you meant by changing to this?

```java
when(mockRequestWithDefaults.getReader()).thenReturn(new BufferedReader(new StringReader(query)));
when(mockRequestNoDefaults.getReader()).thenReturn(new BufferedReader(new StringReader(query)));

Comment (ebyhr) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:417]: Yes.

Comment (Chaho12) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java]: ok :) thx for feedbacks. Learning alot

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java (hunk 5 above)
Comment (Chaho12) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java]: oh `containsExactlyInAnyOrder` simplifies assert !
```java
        assertThat(tablesWithDefaults).containsExactlyInAnyOrder(
                QualifiedName.of("uno"),
                QualifiedName.of("dos"),
                QualifiedName.of("cat", "schem", "tbl1")
        );
```

**Review by willmostly — CHANGES_REQUESTED** [review]
it looks like we are preserving with clause names in the tables list - I think we should exclude them. Lets discuss if needed

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 7]
```diff
@@ -404,6 +404,41 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+        when(mockRequestWithDefaults.getReader()).thenReturn(new BufferedReader(new StringReader(query)));
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_CATALOG_HEADER_NAME)).thenReturn(DEFAULT_CATALOG);
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_SCHEMA_HEADER_NAME)).thenReturn(DEFAULT_SCHEMA);
+
+        TrinoQueryProperties trinoQueryPropertiesWithDefaults = new TrinoQueryProperties(mockRequestWithDefaults, requestAnalyzerConfig);
+
+        Set<QualifiedName> tablesWithDefaults = trinoQueryPropertiesWithDefaults.getTables();
+        assertThat(tablesWithDefaults).containsExactlyInAnyOrder(
+                QualifiedName.of("uno"),
+                QualifiedName.of("dos"),
```
[the remark this answers is not in the document]
Comment (Chaho12) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:426]: Hmm.. so tables is for real tables that is read without temporary ones. Sure will change it :)

File: gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java [hunk 8]
```diff
@@ -385,6 +400,7 @@ private QualifiedName qualifyName(QualifiedName table)
             throws RequestParsingException
     {
         List<String> tableParts = table.getParts();
+
```
Comment (ebyhr) [inline gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java:403]: Revert unrelated change.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 9]
```diff
@@ -404,6 +404,37 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+        when(mockRequestWithDefaults.getReader()).thenReturn(new BufferedReader(new StringReader(query)));
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_CATALOG_HEADER_NAME)).thenReturn(DEFAULT_CATALOG);
+        when(mockRequestWithDefaults.getHeader(TrinoQueryProperties.TRINO_SCHEMA_HEADER_NAME)).thenReturn(DEFAULT_SCHEMA);
+
+        TrinoQueryProperties trinoQueryPropertiesWithDefaults = new TrinoQueryProperties(mockRequestWithDefaults, requestAnalyzerConfig);
+
+        Set<QualifiedName> tablesWithDefaults = trinoQueryPropertiesWithDefaults.getTables();
+        assertThat(tablesWithDefaults).containsExactlyInAnyOrder(
+                QualifiedName.of("cat", "schem", "tbl1")
+        );
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:426]: Unwrap.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java [hunk 10]
```diff
@@ -404,6 +404,37 @@ void testTrinoQueryPropertiesTableExtraction(String query, Set<String> catalogs,
...
+
+        HttpServletRequest mockRequestNoDefaults = prepareMockRequest();
+        when(mockRequestNoDefaults.getReader()).thenReturn(new BufferedReader(new StringReader(query)));
+
+        TrinoQueryProperties trinoQueryPropertiesNoDefaults = new TrinoQueryProperties(mockRequestNoDefaults, requestAnalyzerConfig);
+        Set<QualifiedName> tablesNoDefaults = trinoQueryPropertiesNoDefaults.getTables();
+        assertThat(tablesNoDefaults).containsExactlyInAnyOrder(
+                QualifiedName.of("cat", "schem", "tbl1")
+        );
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:435]: Unwrap.

File: gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java (hunk 9 above)
Comment (Chaho12) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:426]: Sorry i don't understand what you mean by unwrap. Can you suggest changes? Do you mean by one line?
```
assertThat(tablesWithDefaults).containsExactly(QualifiedName.of("cat", "schem", "tbl1"));
```

Comment (ebyhr) [reply gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java:426]: Yes.

File: gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java [hunk 11]
```diff
@@ -336,8 +345,14 @@ private void getNames(Node node, ImmutableSet.Builder<QualifiedName> tableBuilde
...
             case SetViewAuthorization s -> tableBuilder.add(qualifyName(s.getSource()));
-            case Table s -> tableBuilder.add(qualifyName(s.getName()));
+            case Table s -> {
+                // ignore temporary tables as they can have various table parts
+                if (!temporaryTables.contains(s.getName())) {
+                    tableBuilder.add(qualifyName(s.getName()));
+                }
+            }
             case TableFunctionInvocation s -> tableBuilder.add(qualifyName(s.getName()));
+            case WithQuery withQuery -> temporaryTables.add(QualifiedName.of(withQuery.getName().getValue()));
```
Comment (willmostly) [inline gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java:355]: If you revert this to handle `Query` nodes, then we can bypass my concern about encountering a `Table` with a `WithQuery` `name` before it is added to `temporaryTables`. The concern is basically that `node.getChildren()` could return a list with the `QueryBody` before the `With`. If we explicitly process any `With`, then we can ensure that the names are collected before they are referenced. Something like
```
case Query query -> query.getWith().ifPresent(
                    with -> temporaryTables.addAll(with.getQueries().stream().map(WithQuery::getName).map(Identifier::getValue).map(QualifiedName::of).toList()));
```

**Review by willmostly — CHANGES_REQUESTED** [review]

**Comment by mosabua** [comment]
As discussed in the sync I think we should try to get this in asap and then cut 12 - I hope you can collab on that @willmostly @ebyhr and @Chaho12

**Review by willmostly — APPROVED** [review]
lgtm!

**Comment by willmostly** [comment]
Merging for release 12 - further fixups can be done as a follow up
