### PR TITLE
Fix eager evaluation of fallback routing in resolveRouting

### LINKED ISSUE #920: infoUri broken likely due to eager evaluation failure on /ui/query.html
RoutingTargetHandler.resolveRouting() uses Optional.orElse(getRoutingTargetResponse(request)) https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingTargetHandler.java#L83 which eagerly evaluates the fallback even when the query ID is found in the cache. If getRoutingTargetResponse() throws (e.g. no backends match the routing rules), the exception propagates and the request fails with a 500, despite the query ID being successfully resolved.

Steps to reproduce:

1. Configure routing rules that require a specific header (e.g. X-Trino-DC) to determine a routing group, with a catch-all rule that routes to a non-existent group (e.g. drop) when the header is missing
2. Submit a query through the gateway with the required headers — query succeeds and query ID is cached
3. Open the infoUri in a browser: GET /ui/query.html?{queryId} — this request has no X-Trino-DC header

### PR DESCRIPTION
**Pull request by zeckem19**
## Summary

- Change `Optional.orElse()` to `Optional.orElseGet()` in `RoutingTargetHandler.resolveRouting()` to prevent eager evaluation of the fallback path

## Problem

`Optional.orElse(value)` eagerly evaluates `value` , in `resolveRouting()`, this means `getRoutingTargetResponse(request)` is always called, even when the query ID is found in the cache and `previousCluster` is present.

For requests like `GET /ui/query.html?queryId` (e.g. Trino Web UI tracking links via Superset), the request has no routing headers (`X-Trino-Routing-Group`, etc.). When `getRoutingTargetResponse()` runs the routing rules and falls through to `provideBackendConfiguration()`, it throws `IllegalStateException: Number of active backends found zero` if no default backend is configured. This exception propagates before `.orElse()` can return the cached result, causing a 500 error even though the query ID was successfully resolved.

## Fix

Replace `.orElse(getRoutingTargetResponse(request))` with `.orElseGet(() -> getRoutingTargetResponse(request))` so the fallback is only evaluated when `previousCluster` is empty.

## Test plan

- Added `testResolveRoutingWithKnownQueryIdAndFailingFallback` which verifies that when a query ID is found in the cache but the fallback routing would throw, `resolveRouting` still returns the cached backend successfully
- The test fails with `orElse()` and passes with `orElseGet()`

Fixes #920

### CODE REVIEW

**Comment by zeckem19** [comment]
@ebyhr  i added the test, and have emailed the CLA (zeckem19)

File: gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java [hunk 1]
```diff
@@ -300,6 +300,38 @@ void testPropagateErrorsTrueResponseGroupAndErrorsSet()
                 .isInstanceOf(WebApplicationException.class);
     }
 
+    @Test
+    void testResolveRoutingWithKnownQueryIdAndFailingFallback()
+            throws Exception
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java]: Remove redundant `throws Exception`.

File: gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java [hunk 2]
```diff
@@ -300,6 +300,38 @@ void testPropagateErrorsTrueResponseGroupAndErrorsSet()
...
+        // Query ID is known — cache returns the backend
+        when(routingManager.findBackendForQueryId(queryId)).thenReturn(backendUrl);
+        when(routingManager.findRoutingGroupForQueryId(queryId)).thenReturn("test-group");
+        when(routingManager.findExternalUrlForQueryId(queryId)).thenReturn(backendUrl);
+
+        // Fallback routing would throw (no backends for the routing group)
+        when(routingManager.provideBackendConfiguration(any(), any()))
+                .thenThrow(new IllegalStateException("Number of active backends found zero"));
+
+        // With orElse(), this throws. With orElseGet(), this succeeds.
```
Comment (ebyhr) [inline gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java]: I don't think readers can understand the meaning of this comment. The place of `orElse()` & `orElseGet()` are totally unclear. Please add a link to `https://github.com/trinodb/trino-gateway/issues/920`.

**Comment by ebyhr** [comment]
Please fix CI failure: 
```
Error:  src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java:[310] (regexp) RegexpMultiline: Line has trailing whitespace
```

Also, please follow the PR template next time.

**Comment by vaultah** [comment]
Thanks for fixing this. Just two cents/impact statement: 

In trino-gateway 16, `QueryCountBasedRouter` overrode `provideBackendConfiguration` and selected from its in-memory `clusterStats` via `getBackendConfigurationForRoutingGroup`.

In trino-gateway 17, `QueryCountBasedRouter` no longer overrides `provideBackendConfiguration`. The inherited `BaseRoutingManager` method _always_ does a DB call.

Practically this means that when using `QueryCountBasedRouter`, due to the eager `getRoutingTargetResponse` evaluation, trino-gateway 17 performs one or two DB calls for every routing decision/request.

**Comment by zeckem19** [comment]
> Please fix CI failure:
> 
> ```
> Error:  src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java:[310] (regexp) RegexpMultiline: Line has trailing whitespace
> ```
> 
> Also, please follow the PR template next time.

i think this should already be fixed, how do i re-run ci?

**Comment by ebyhr** [comment]
@zeckem19 Please check the latest failure. It's failing with a different error: 
```
Error:  Errors: 
Error:    TestRoutingTargetHandler.testBasicHeaderModification:135 » IllegalState Number of active backends found zero
Error:    TestRoutingTargetHandler.testEmptyHeader:202 » IllegalState Number of active backends found zero
Error:    TestRoutingTargetHandler.testExcludedHeaders:159 » IllegalState Number of active backends found zero
Error:    TestRoutingTargetHandler.testNoHeaderModification:180 » IllegalState Number of active backends found zero
Error:    TestRoutingTargetHandler.testPropagateErrorsFalseResponseGroupNullResponseErrorsSet:262 » IllegalState Number of active backends found zero
Error:    TestRoutingTargetHandler.testResponseGroupSetResponseErrorsNull:251 » IllegalState Number of active backends found zero
Error:    TestRoutingTargetHandler.testResponsePropertiesNull:239 » IllegalState Number of active backends found zero
```

**Comment by zeckem19** [comment]
added reset with  `@BeforeEach`  to reset the tests

**Comment by zeckem19** [comment]
@ebyhr could we rerun the CI

**Comment by zeckem19** [comment]
@ebyhr  sorry, again please

**Comment by mosabua** [comment]
@oneonestar @ebyhr @zeckem19 - could you provide a suggestion for the release notes entry for this PR and the related issue please

**Comment by zeckem19** [comment]
> @oneonestar @ebyhr @zeckem19 - could you provide a suggestion for the release notes entry for this PR and the related issue please

how about
```
Fixed bug with eager evaluation of fallback routing for queries 
```
